### ISSUE TITLE
Error: `libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by bencullimore** [nhsalpha/nhs_prototype_kit#180]
Hi, I'm having an issue running your kit. Help! I'm on a Apple Mac, OS X 10.11.2, node version 4.2.3

When I run 'node start js' I'm getting: 

```
Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found. Try reinstalling `node-sass`?
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.
```

I then try reinstalling node-sass and get

```
Bens-MacBook-Pro-2:nhs_prototype_kit bencullimore$ npm rebuild node-sass

> node-sass@2.1.1 install /Users/bencullimore/nhs_prototype_kit/node_modules/node-sass
> node scripts/install.js


> node-sass@2.1.1 postinstall /Users/bencullimore/nhs_prototype_kit/node_modules/node-sass
> node scripts/build.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/bencullimore/nhs_prototype_kit/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
Build failed
node-sass@2.1.1 /Users/bencullimore/nhs_prototype_kit/node_modules/node-sass
Bens-MacBook-Pro-2:nhs_prototype_kit bencullimore$ 
```

I've has a look around and it might be something to do with the version of node I'm running. 

Any ideas? Thanks!

**Comment by joelanman** [comment]
Yeh this is normally due to the version of node. You can install and run different versions using NVM:

https://github.com/creationix/nvm

alternatively you can try updating the version of grunt-sass:

```
npm uninstall --save grunt-sass
npm install --save grunt-sass
```

**Comment by bencullimore** [comment]
Thanks Joe, thats sorted it! Much appreciated.
